DAL init
Leeyaoi/InnoViber pull request #1
Opened 2024-06-04 12:42 UTC by Leeyaoi

2024-06-04 15:43 UTC, pavelGagarin0870 requested changes

2024-06-04 15:43 UTC, pavelGagarin0870 commented on InnoViber.DAL/User.cs
> +        public int Id { get; set; }
Better to use Guid instead off Int

2024-06-04 15:43 UTC, pavelGagarin0870 commented on InnoViber.DAL/User.cs
> +        public string Name { get; set; } = "";
string.Empty instead of ""

2024-06-04 15:43 UTC, pavelGagarin0870 commented on InnoViber.DAL/Chat.cs
> +        public int ID { get; set; }
ID )

2024-06-04 15:43 UTC, pavelGagarin0870 commented on InnoViber.DAL/Message.cs
> +        public User User { get; set; } = new();
Make nullable and remove new();

2024-06-04 15:43 UTC, pavelGagarin0870 commented on InnoViber.DAL/Message.cs
> +        public User User { get; set; } = new();
Nullable because we may not use Includes and Loading

2024-06-04 16:38 UTC, pavelGagarin0870 approved these changes

2024-06-04 21:02 UTC, pavelGagarin0870 approved these changes

2024-06-04 21:02 UTC, pavelGagarin0870 commented on InnoViber.DAL/Chat.cs
> +﻿namespace InnoViber.DAL
File scoped namespaces

2024-06-04 21:02 UTC, pavelGagarin0870 commented on InnoViber.DAL/Message.cs
> +namespace InnoViber.DAL
File scoped namespaces

2024-06-04 21:02 UTC, pavelGagarin0870 commented on InnoViber.DAL/User.cs
> +namespace InnoViber.DAL
File scoped namespaces

2024-06-05 08:40 UTC, MaliyOna approved these changes

2024-06-05 08:43 UTC, merged