Added db context & migrations
Leeyaoi/InnoViber pull request #4
Opened 2024-06-05 14:19 UTC by Leeyaoi

2024-06-05 14:22 UTC, moltenessence requested changes

2024-06-05 14:22 UTC, moltenessence commented on InnoViber.DAL/Message.cs
> +    public Chat? Chat { get; set; }
Ids are missed: UserId, ChatId

2024-06-05 14:22 UTC, moltenessence commented on InnoViber/Program.cs
> +            });
why hardcoded here?

2024-06-05 14:26 UTC, pavelGagarin0870 requested changes

2024-06-05 14:26 UTC, pavelGagarin0870 commented on InnoViber/Program.cs
> +            });
Delete commented code, retrieve connection string from AppSettings

2024-06-05 14:26 UTC, pavelGagarin0870 commented on InnoViber/Program.cs
> +            builder.Services.AddDbContext<ViberContext>(option =>
Move this part of DI to DAL layer

2024-06-06 06:24 UTC, moltenessence approved these changes

2024-06-06 07:16 UTC, pavelGagarin0870 approved these changes

2024-06-06 07:24 UTC, merged